EGG_TOTALS_IDS = {
    "edible": 0,
    "superfood": 1,
    "medical": 2,
    "rocket_fuel": 3,
    "super_material": 4,
    "fusion": 5,
    "quantum": 6,
    "immortality": 7,
    "tachyon": 8,
    "graviton": 9,
    "dilithium": 10,
    "prodigy": 11,
    "terraform": 12,
    "antimatter": 13,
    "dark_matter": 14,
    "ai": 15,
    "nebula": 16,
    "universe": 17,
    "enlightenment": 18,
}
