MAP_EGG_NAME_ID = {
    "edible": 0,
    "superfood": 1,
    "medical": 2,
    "rocket_fuel": 3,
    "super_material": 4,
    "fusion": 5,
    "quantum": 6,
    "immortality": 7,
    "tachyon": 8,
    "graviton": 9,
    "dilithium": 10,
    "prodigy": 11,
    "terraform": 12,
    "antimatter": 13,
    "dark_matter": 14,
    "ai": 15,
    "nebula": 16,
    "universe": 17,
    "enlightenment": 18,
}

MAP_EPIC_EI_TO_CALC = {
    "hold_to_hatch": "holdToHatch",
    "epic_hatchery": "epicHatchery",
    "epic_internal_incubators": "epicIntHatchery",
    "video_doubler_time": "videoDoubler",
    "epic_clucking": "epicClucking",
    "epic_multiplier": "epicMultiplier",
    "cheaper_contractors": "cheaperContractors",
    "bust_unions": "bustUnions",
    "cheaper_research": "labUpgrade",
    "epic_silo_quality": "siloQuality",  # no longer present
    "silo_capacity": "siloCapacity",
    "int_hatch_sharing": "internalHatcherySharing",
    "int_hatch_calm": "internalHatcheryCalm",
    "accounting_tricks": "accountingTricks",
    "hold_to_research": "holdToResearch",
    "soul_eggs": "soulFood",
    "prestige_bonus": "prestigeBonus",
    "drone_rewards": "droneRewards",
    "epic_egg_laying": "epicComfyNests",
    "transportation_lobbyist": "transportationLobbyists",
    "warp_shift": "warpShift",  # no longer present
    "prophecy_bonus": "prophecyBonus",
    "afx_mission_time": "ftlDrive",
    "afx_mission_capacity": "zeroG",
}

# From the Egg, Inc. Discord server
MAP_OOM_FARMER_ROLE = {
    "0": "Farmer",
    "1": "Farmer II",
    "2": "Farmer III",
    "3": "Kilofarmer",
    "4": "Kilofarmer II",
    "5": "Kilofarmer III",
    "6": "Megafarmer",
    "7": "Megafarmer II",
    "8": "Megafarmer III",
    "9": "Gigafarmer",
    "10": "Gigafarmer II",
    "11": "Gigafarmer III",
    "12": "Terafarmer",
    "13": "Terafarmer II",
    "14": "Terafarmer III",
    "15": "Petafarmer",
    "16": "Petafarmer II",
    "17": "Petafarmer III",
    "18": "Exafarmer",
    "19": "Exafarmer II",
    "20": "Exafarmer III",
    "21": "Zettafarmer",
    "22": "Zettafarmer II",
    "23": "Zettafarmer III",
    "24": "Yottafarmer",
    "25": "Yottafarmer II",
    "26": "Yottafarmer III",
    "27": "Xennafarmer",
    "28": "Xennafarmer II",
    "29": "Xennafarmer III",
    "30": "Weccafarmer",
    "31": "Weccafarmer II",
    "32": "Weccafarmer III",
    "33": "Vendafarmer",
    "34": "Vendafarmer II",
    "35": "Vendafarmer III",
    "36": "Uadafarmer",
    "37": "Uadafarmer II",
    "38": "Uadafarmer III",
    "39": "Treidafarmer",
    "40": "Treidafarmer II",
    "41": "Treidafarmer III",
    "42": "Quadafarmer",
    "43": "Quadafarmer II",
    "44": "Quadafarmer III",
    "45": "Pendafarmer",
    "46": "Pendafarmer II",
    "47": "Pendafarmer III",
    "48": "Exedafarmer",
    "49": "Exedafarmer II",
    "50": "Exedafarmer III",
    "51": "Infinifarmer",
}
