EGG_TOTALS_IDS = {
    "edible": 0,
    "superfood": 1,
    "medical": 2,
    "rocket_fuel": 3,
    "super_material": 4,
    "fusion": 5,
    "quantum": 6,
    "immortality": 7,
    "tachyon": 8,
    "graviton": 9,
    "dilithium": 10,
    "prodigy": 11,
    "terraform": 12,
    "antimatter": 13,
    "dark_matter": 14,
    "ai": 15,
    "nebula": 16,
    "universe": 17,
    "enlightenment": 18,
}

MAP_EPIC_EI_TO_CALC = {
    "hold_to_hatch": "holdToHatch",
    "epic_hatchery": "epicHatchery",
    "epic_internal_incubators": "epicIntHatchery",
    "video_doubler_time": "videoDoubler",
    "epic_clucking": "epicClucking",
    "epic_multiplier": "epicMultiplier",
    "cheaper_contractors": "cheaperContractors",
    "bust_unions": "bustUnions",
    "cheaper_research": "labUpgrade",
    "epic_silo_quality": "siloQuality",  # no longer present
    "silo_capacity": "siloCapacity",
    "int_hatch_sharing": "internalHatcherySharing",
    "int_hatch_calm": "internalHatcheryCalm",
    "accounting_tricks": "accountingTricks",
    "hold_to_research": "holdToResearch",
    "soul_eggs": "soulFood",
    "prestige_bonus": "prestigeBonus",
    "drone_rewards": "droneRewards",
    "epic_egg_laying": "epicComfyNests",
    "transportation_lobbyist": "transportationLobbyists",
    "warp_shift": "warpShift",  # no longer present
    "prophecy_bonus": "prophecyBonus",
    "afx_mission_time": "ftlDrive",
    "afx_mission_capacity": "zeroG",
}
